set("DEPENDS_ON_PACKAGES" "x11" CACHE INTERNAL "")
set("DEPENDS_ON_PACKAGES" "${DEPENDS_ON_PACKAGES}" "xext" CACHE INTERNAL "")
set("DEPENDS_ON_PACKAGES" "${DEPENDS_ON_PACKAGES}" "xextproto" CACHE INTERNAL "")
set("DEPENDS_ON_PACKAGES" "${DEPENDS_ON_PACKAGES}" "xineramaproto" CACHE INTERNAL "")
