set("DRISHTI_BUILD_EXAMPLES" "NO" CACHE INTERNAL "")
set("DRISHTI_BUILD_OGLES_GPGPU" "ON" CACHE INTERNAL "")
set("DRISHTI_BUILD_SHARED_SDK" "OFF" CACHE INTERNAL "")
set("DRISHTI_OPENGL_ES3" "OFF" CACHE INTERNAL "")
