set("ASSIMP_BUILD_ASSIMP_TOOLS" "OFF" CACHE INTERNAL "")
set("ASSIMP_BUILD_SAMPLES" "OFF" CACHE INTERNAL "")
set("ASSIMP_BUILD_TESTS" "OFF" CACHE INTERNAL "")
set("ASSIMP_ENABLE_BOOST_WORKAROUND" "OFF" CACHE INTERNAL "")
