set("BUILD_TESTING" "OFF" CACHE INTERNAL "")
set("CIVETWEB_ENABLE_ASAN" "OFF" CACHE INTERNAL "")
set("CIVETWEB_ENABLE_SSL_DYNAMIC_LOADING" "OFF" CACHE INTERNAL "")
set("CIVETWEB_INSTALL_EXECUTABLE" "OFF" CACHE INTERNAL "")
