set("ACF_BUILD_OGLES_GPGPU" "ON" CACHE INTERNAL "")
set("ACF_USE_DRISHTI_CACHE" "OFF" CACHE INTERNAL "")
set("ACF_BUILD_EXAMPLES" "OFF" CACHE INTERNAL "")
set("ACF_BUILD_TESTS" "OFF" CACHE INTERNAL "")
